-- Manual transactions may be permanently deleted by their owner. Technical
-- rows generated by invoices, scheduled items, or investments stay protected.
drop policy if exists "transactions_owner_delete_manual"
on public.transactions;

create policy "transactions_owner_delete_manual"
on public.transactions
for delete
to authenticated
using (
  (select auth.uid()) = user_id
  and origin_type::text = 'manual'
);

grant delete on table public.transactions to authenticated;
