import Link from "next/link";
import { closeMonthlyCheckin } from "@/app/actions/monthly-checkins";
import { currentReferenceMonth, toReferenceMonth } from "@/domain/budgets";
import { formatMoney } from "@/domain/money";
import { getCurrentUserMonthlyCheckin } from "@/services/finance/monthly-checkins-service";
import { formatIsoDatePtBr } from "@/utils/dates";

export const metadata = { title: "Check-in financeiro" };

const messages = { closed: "Fechamento mensal confirmado.", error: "Não foi possível concluir o check-in." };

function ChecklistCard({ number, title, description, count, href, tone = "slate", children }: { number: number; title: string; description: string; count?: number; href: string; tone?: "slate" | "amber" | "emerald"; children?: React.ReactNode }) {
  const colors = tone === "amber" ? "border-amber-200 bg-amber-50" : tone === "emerald" ? "border-emerald-200 bg-emerald-50" : "border-slate-200 bg-white";
  return <article className={`rounded-xl border px-3 py-3 sm:px-4 ${colors}`}><div className="flex items-start gap-3"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-slate-950 text-xs font-black text-white">{number}</span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><h2 className="text-sm font-black text-slate-950 sm:text-base">{title}</h2><p className="mt-0.5 text-xs leading-5 text-slate-600 sm:text-sm">{description}</p></div>{count !== undefined ? <span className="shrink-0 text-xl font-black leading-none text-slate-950 sm:text-2xl">{count}</span> : null}</div><div className="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1">{children}<Link href={href} className="text-xs font-bold text-emerald-800 hover:text-emerald-950 sm:text-sm">Revisar →</Link></div></div></div></article>;
}

export default async function CheckInPage({ searchParams }: { searchParams: Promise<{ month?: string; message?: string }> }) {
  const params = await searchParams;
  const month = /^\d{4}-\d{2}$/.test(params.month ?? "") ? params.month! : currentReferenceMonth();
  const data = await getCurrentUserMonthlyCheckin(toReferenceMonth(month));
  const { checklist, checkin } = data;
  const totalTasks = [checklist.unclassifiedCount, checklist.unreconciledCount, checklist.upcomingInvoices.length, checklist.overBudget.length, checklist.staleQuotes.length].filter((count) => count > 0).length;
  const done = checkin?.status === "closed";
  return <main className="mx-auto grid max-w-4xl gap-4 px-3 py-4 sm:px-6 sm:py-6"><header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-emerald-700">Rotina financeira</p><h1 className="mt-1 text-2xl font-black tracking-tight text-slate-950 sm:text-3xl">Check-in mensal</h1><p className="mt-1 max-w-xl text-xs text-slate-600 sm:text-sm">Um passo a passo curto para deixar o mês organizado antes de seguir em frente.</p></div><form method="get" className="flex w-full items-center gap-2 sm:w-auto"><label htmlFor="check-in-month" className="sr-only">Mês do check-in</label><input id="check-in-month" type="month" name="month" defaultValue={month} className="min-h-9 min-w-0 flex-1 rounded-lg border border-slate-300 bg-white px-3 text-sm font-semibold shadow-sm sm:flex-none" /><button className="min-h-9 rounded-lg bg-slate-950 px-3 text-xs font-bold text-white">Abrir</button></form></header>
    {params.message && messages[params.message as keyof typeof messages] ? <p role={params.message === "error" ? "alert" : "status"} className={`rounded-xl border px-4 py-3 text-sm ${params.message === "error" ? "border-red-200 bg-red-50 text-red-800" : "border-emerald-200 bg-emerald-50 text-emerald-800"}`}>{messages[params.message as keyof typeof messages]}</p> : null}
    {data.hasError ? <p role="alert" className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">Algumas verificações não puderam ser carregadas. Revise os módulos indicados diretamente.</p> : null}
    <section className="flex flex-col gap-2 rounded-xl bg-slate-950 p-4 text-white sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[11px] font-extrabold uppercase tracking-[0.16em] text-emerald-300">{formatIsoDatePtBr(data.referenceMonth)}</p><h2 className="mt-1 text-lg font-black">{done ? "Mês fechado" : "Vamos revisar este mês"}</h2><p className="mt-0.5 text-xs text-slate-300 sm:text-sm">{done ? "Fechamento confirmado." : totalTasks ? `${totalTasks} etapa${totalTasks === 1 ? "" : "s"} merece${totalTasks === 1 ? "" : "m"} atenção.` : "Nenhuma pendência crítica encontrada."}</p></div><span className={`self-start rounded-full px-2.5 py-1 text-xs font-bold sm:self-auto ${done ? "bg-emerald-300 text-emerald-950" : "bg-white/10 text-white"}`}>{done ? "Concluído" : "Em aberto"}</span></section>
    <section className="grid gap-2"><ChecklistCard number={1} title="Lançamentos sem classificação" description="Categorias ajudam relatórios e orçamento." count={checklist.unclassifiedCount} href="/transactions" tone={checklist.unclassifiedCount ? "amber" : "emerald"}>{checklist.unclassifiedCount ? <span className="text-xs font-bold text-amber-800">Atenção necessária</span> : <span className="text-xs font-bold text-emerald-800">Tudo classificado</span>}</ChecklistCard><ChecklistCard number={2} title="Reconciliação" description="Confirme o que já foi conferido no extrato." count={checklist.unreconciledCount} href="/accounts" tone={checklist.unreconciledCount ? "amber" : "emerald"}>{checklist.unreconciledCount ? <span className="text-xs font-bold text-amber-800">Movimentações pendentes</span> : <span className="text-xs font-bold text-emerald-800">Extratos conferidos</span>}</ChecklistCard><ChecklistCard number={3} title="Próximas contas e faturas" description="Antecipe recorrências e cartões nos próximos 45 dias." count={checklist.upcomingInvoices.length + checklist.upcomingRecurrencesCount} href="/accounts"><span className="text-xs text-slate-600">{checklist.upcomingInvoices.length} fatura{checklist.upcomingInvoices.length === 1 ? "" : "s"} · {checklist.upcomingRecurrencesCount} recorrência{checklist.upcomingRecurrencesCount === 1 ? "" : "s"}</span>{checklist.upcomingInvoices.length ? <span className="text-xs font-bold text-slate-900">{formatMoney(checklist.upcomingInvoices.reduce((sum, invoice) => sum + invoice.outstanding_amount_minor, 0), checklist.upcomingInvoices[0].currency)}</span> : null}</ChecklistCard><ChecklistCard number={4} title="Categorias acima do orçamento" description="Veja o que chegou a 80% ou ultrapassou o planejado." count={checklist.overBudget.length} href="/budgets" tone={checklist.overBudget.length ? "amber" : "emerald"}>{checklist.overBudget.slice(0, 3).map((row) => <span key={row.category_id} className="rounded-full bg-white/70 px-2 py-1 text-xs font-bold text-slate-700">{row.category_name} {row.percentage_consumed.toLocaleString("pt-BR")} %</span>)}</ChecklistCard><ChecklistCard number={5} title="Cotações vencidas" description="Atualize posições sem cotação há mais de 30 dias." count={checklist.staleQuotes.length} href="/investments/prices" tone={checklist.staleQuotes.length ? "amber" : "emerald"}>{checklist.staleQuotes.slice(0, 3).map((row) => <span key={row.id} className="text-xs text-slate-600">{row.asset_name} · {formatIsoDatePtBr(row.position_date)}</span>)}</ChecklistCard></section>
    <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-emerald-700">Fechamento</p><h2 className="mt-1 text-lg font-black text-slate-950">Como foi o resultado?</h2><p className="mt-1 text-xs text-slate-600 sm:text-sm">Opcional: deixe uma nota curta para consultar no histórico deste mês.</p></div>{done ? <div className="mt-3 rounded-lg bg-slate-50 p-3 text-sm text-slate-700">{checkin?.observation || "Nenhuma observação foi registrada."}</div> : <form action={closeMonthlyCheckin} className="mt-3 grid gap-3"><input type="hidden" name="referenceMonth" value={data.referenceMonth} /><textarea name="observation" rows={3} maxLength={2000} placeholder="Ex.: reduzi gastos com delivery." className="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100" /><button className="min-h-10 rounded-lg bg-emerald-700 px-4 text-sm font-bold text-white hover:bg-emerald-800">Confirmar fechamento</button></form>}</section>
  </main>;
}
